# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f242fccc6d0217c2404f2bdcf61de7fd3bdae3143558ff9ef5e96b792b34067d76972f06478338022c3a9446a9708f676f456f7e84d1fdb8e435b0a39d7884aa

test:
  secret_key_base: b8a8a8b54a0acc3c33b3156eb1bcb01f58aaf5eccdc41c31265e1240e9ae469ff2ad52b71a4c20a3e93bc2d8dab75b45bda5828a4e1a3a6e768a6e2dcb06aa5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
